### PR TITLE
Update redux-store.html

### PR DESCRIPTION
**Pull request by mdibenedetto**
I suggest to add support for REDUX dev tool extension used in Chrome, is very handy to have a panel which shows the timeline of changes in your state, to do that you need to use " window.devToolsExtension() or window.__REDUX_DEVTOOLS_EXTENSION__" and Redux.compose().

const store = Redux.createStore(
reducer,
Redux.compose(
Redux.applyMiddleware(ReduxThunk.default),
window.devToolsExtension && window.devToolsExtension()
));

### CODE REVIEW

**Comment by johnthad** [comment]
Since the typical user won't have the Redux DevTools extension installed, is there a way that does not require two versions of the redux-store.html? Without the extension, the page fails in Chrome 61 and 63/Canary with

```
redux.js:714 Uncaught TypeError: Cannot read property 'apply' of undefined
    at redux.js:714
    at Object.createStore (redux.js:290)
    at redux-store.html:38
```

**Comment by mdibenedetto** [comment]
right, I see the error.. let  me  check

**Comment by johnthad** [comment]
I would have thought so, too (_nice_ plugin, BTW). It works with your change for Polycast 61, but not with this one. If I disable or uninstall the plugin, I get the error above (I also tried with Adblock Plus and Ghostrery disabled).

Is your `package-lock.json` for Redux the same? Mine is

```
"redux": {
  "version": "3.7.0",
  "resolved": "https://registry.npmjs.org/redux/-/redux-3.7.0.tgz",
  "integrity": "sha512-GHjaOkEQtQnnuLoYPFkRKHIqs1i1tdTlisu/xUHfk2juzCobSy4STxs4Lz5bPkc07Owb6BeGKx/r76c9IVTkOw==",
  "requires": {
    "lodash": "4.17.4",
    "lodash-es": "4.17.4",
    "loose-envify": "1.3.1",
    "symbol-observable": "1.0.4"
  }
},
"redux-thunk": {
  "version": "2.2.0",
  "resolved": "https://registry.npmjs.org/redux-thunk/-/redux-thunk-2.2.0.tgz",
  "integrity": "sha1-5hWhbha0ehmlFXZhM9Hj6Zt4UuU="
},
```

**Comment by mdibenedetto** [comment]
this solution should work pretty fine

  var store = Redux.createStore(
    reducer,
    Redux.compose(
      Redux.applyMiddleware(ReduxThunk.default), 
      window.devToolsExtension ?
      window.devToolsExtension() :
      v => v
    ));

**Comment by mdibenedetto** [comment]
btw I think It works with polycast61 because there we do not use ** Redux.compose** if I remember well

**Comment by johnthad** [comment]
Yes. That works with or without the extension. I'll pull this in later today or tomorrow. Thanks.

**Comment by mdibenedetto** [comment]
great

**Pull request merged**
